### ISSUE TITLE
HTML5 Input Types

### ISSUE THREAD

**Issue by jackbentley** [phillipsdata/minphp-form#3]
There's no public methods for HTML 5 input field types such as `number`, etc - 
https://www.w3.org/TR/html5/forms.html#attr-input-type

The super-method `fieldInput` is private, so there's absolutely no way to create such fields.

**Comment by tysonphillips** [comment]
Sure you can 😄 Input fields are simply text fields with a different **type** attribute.

```
use Minphp\Form\Form;

$form = new Form();
$form->create();
$form->fieldText('Field', 25, array('type' => 'number'));
$form->end();
```

**Comment by jackbentley** [comment]
Ah. Well, now I look silly! 😅 

I guess that's what happens with late night coding on unfamiliar code and only looking at the method signatures!
